spring.application.name=gerenciador-eventos

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_eventos
spring.datasource.username=${DB_USERNAME:******}
spring.datasource.password=${DB_PASSWORD:******}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.admin.nome=${ADMIN_NOME:Administrador Principal}
app.admin.email=${ADMIN_EMAIL:admin@gerenciadoreventos.com}
app.admin.senha=${ADMIN_SENHA:Admin@123456}

api.security.token.secret=${JWT_SECRET:chave-jwt-desenvolvimento-32-bytes-minimo-123456}


